"""
fix musiccaps paths generated by muchomusic
"""

import os
import json
import re

if __name__ == "__main__":
    # input_file = "input_data/muchomusic_original.json"
    input_file = "input_data/muchomusic_random.json"

    with open(input_file, "r") as f:
        data = json.load(f)

    new_output = data.copy()

    # thanks chatgpt
    pattern = r"\[(\S+)\]-\[(\d+)-\d+\]"

    for idx, q in enumerate(data):
        if q["dataset"] == "musiccaps":
            audio_path = q["audio_path"]
            base_folder = os.path.dirname(audio_path)

            match = re.search(pattern, audio_path)

            if match:
                ytid = match.group(1)
                start = match.group(2)
                new_name = f"{ytid}_{start}.wav"
                new_audio_path = os.path.join(base_folder, new_name)
                new_output[idx]["audio_path"] = new_audio_path
            else:
                print("No match!")

    with open(input_file, "w") as f:
        json.dump(new_output, f)
