"""
fix musiccaps paths generated by muchomusic
"""

import argparse
import os
import json
import re


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Fix audio paths for MusicCaps when the input is generated by MuChoMusic's prepare_prompts script"
    )
    parser.add_argument(
        "--input_path",
        type=str,
        required=True,
        default=None,
    )
    parser.add_argument(
        "--output_path",
        type=str,
        required=True,
        default=None,
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_arguments()

    with open(args.input_path, "r") as f:
        data = json.load(f)

    new_output = data.copy()

    # thanks chatgpt
    pattern = r"\[(\S+)\]-\[(\d+)-\d+\]"

    for idx, q in enumerate(data):
        if q["dataset"] == "musiccaps":
            audio_path = q["audio_path"]
            base_folder = os.path.dirname(audio_path)

            match = re.search(pattern, audio_path)

            if match:
                ytid = match.group(1)
                start = match.group(2)
                new_name = f"{ytid}_{start}.wav"
                new_audio_path = os.path.join(base_folder, new_name)
                new_output[idx]["audio_path"] = new_audio_path

    with open(args.output_path, "w") as f:
        json.dump(new_output, f)
